### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [slomkowski/microlab-speakers-remote-hijack#1]
Hello!

I found link to this project from https://hackaday.com/2020/11/24/digispark-spoofs-ir-to-get-speakers-under-control/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

**Comment by slomkowski** [comment]
I added BSD 3 license.

**Comment by vazhnov** [comment]
@slomkowski , thank you very much!
